# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
jobs:
  - job: 'Run Tests'
    pool:
      vmImage: 'Ubuntu 16.04'
    strategy:
      matrix:
        Python27:
          python.version: '2.7.15'
        Python35:
          python.version: '3.5.5'
        Python36:
          python.version: '3.6.5'
        Python37:
          python.version: '3.7.0'
      maxParallel: 4
      
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(python.version)
        architecture: 'x64'

    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'secrets.py'

    - task: CopyFiles@2
      inputs:
        sourceFolder: $(Agent.TempDirectory)
        contents: 'secrets.py' 
        targetFolder: $(Agent.BuildDirectory)/s/test/
        overWrite: true

    - script: pip install --user -r requirements.txt
      displayName: 'Setup tox for testing'

    - script: /home/vsts/.local/bin/pytest --junitxml=junit/test-results.xml
      displayName: 'Run unit tests'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: 'Publish test results for Python $(python.version)'

  - job: 'Build and deploy'
    pool:
      vmImage: 'Ubuntu 16.04'
    
    steps:
      - task: CopyFiles@2
        inputs:
          sourceFolder: $(Agent.TempDirectory)
          contents: 'secrets.py' 
          targetFolder: $(Agent.BuildDirectory)/s/test/
          overWrite: true

      - script: python setup.py sdist
        displayName: 'Build source distribution'
      
      - task: PublishBuildArtifacts@1
        displayName: 'Publish artifact: release'
        inputs:
          pathtoPublish: 'dist'
          artifactName: 'release'



